language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - yarn install
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot
script: yarn run test
